### ISSUE TITLE
Kubernetes plugin uses hardcoded path for calicoctl

### ISSUE THREAD

**Issue by hvolkmer** [projectcalico/calico-docker#201]
The calico kubernetes plugin uses a hardcoded path to  `/home/vagrant/calicoctl`:

```
 Traceback (most recent call last):
   File "<string>", line 14, in <module>
   File "/code/build/calico_kubernetes/out00-PYZ.pyz/sh", line 788, in __init__
 sh.CommandNotFound: /home/vagrant/calicoctl
```

If this is deployed on systems that don't have a vagrant user and the calicoctl binary in this directory, the plugin does not work. 

Expected: The plugin should try to find the `calicoctl` in `$PATH`.

**Comment by lxpollitt** [comment]
@hvolkmer Are you able to workaround the issue in the short term?  We definitely will fix but want to understand the immediate urgency for you so we prioritize appropriately.

**Comment by hvolkmer** [comment]
Currently I just create the directory and symlink the real `calicoctl` to the expected path. That works. I just  wanted to file the issue so that it won't be forgotten.

**Comment by caseydavenport** [comment]
The most recent version of the Kubernetes plugin allows the path to calicoctl to be specified using the CALICOCTL_PATH environment variable.  This value defaults to "/usr/bin/calicoctl".

Take a look at this doc for some more details: https://github.com/projectcalico/calico-docker/blob/master/docs/kubernetes/KubernetesIntegration.md

Eventually, future releases will remove the dependency on calicoctl entirely, relying on libcalico for configuration.
