### ISSUE TITLE
Calicoctl subcommands have broken bash autocomplete

### ISSUE THREAD

**Issue by tomdee** [projectcalico/calico-docker#328]

**Comment by devopsmyth** [comment]
I'd like to reopen this as I'm experiencing this issue currently.

**Comment by caseydavenport** [comment]
@devopsmyth could you open a new issue describing what you're seeing? This one is old and doesn't have any details on it.

**Comment by devopsmyth** [comment]
> @devopsmyth could you open a new issue describing what you're seeing? This one is old and doesn't have any details on it.

Of course!
