### ISSUE TITLE
Some containers in same network get different profile IDs

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico-docker#365]
Running a scale test with 3 hosts, libnetwork, consul.  Spun up 100 pinger containers on each host as a random mesh of pings.  About 40% of containers never got a ping through to their peer.

Looking at iptables, I traced the path of the failing packets to the IP address of the source being missing from the ipset.  It turned out that the source and dest containers had ended up in different calico profiles, despite being started with the same `--pubish-service` network suffix "net1.calico".

There were other containers on the same pair of hosts that did manage to ping each other so the problem appears to be intermittent.

**Comment by tomdee** [comment]
Some questions:
* Need to know if this is only affecting just containers on different hosts?
  * You think it happens to containers on the same host
* Is there a time aspect on this? Does it affect just the first N containers, or is it a random selection of containers?
* How quickly are you spinning up containers?

**Comment by tomdee** [comment]
Can you also provide logs from your docker daemons?

**Comment by fasaxc** [comment]
I sent you a diags bundle for this issue, collected with "calicoctl diags".

**Comment by tomdee** [comment]
This is probably an instance of https://github.com/docker/libnetwork/issues/337

Without an easy repro we can't drill down on this. Given it's already tracked upstream, I'm closing this issue.
