### ISSUE TITLE
ipip kernel module should not be required if not running --ipip

### ISSUE THREAD

**Issue by spikecurtis** [projectcalico/calico-docker#368]

**Comment by tomdee** [comment]
This affects our calicoctl checksystem command.

Other than that, I think it's a matter of configuring felix properly. And I'm not sure if felix supports the configuration we need yet.

We probably want to do something like only enabling IPIP in felix once a pool has been created that enables IPIP. Until then, the IPIP module shouldn't be loaded or at least the tun0 device shouldn't be created.

**Comment by spikecurtis** [comment]
Felix supports this now and will apply config changes immediately  https://github.com/projectcalico/calico/pull/749

**Comment by robbrockbank** [comment]
I've made a change to libcalico to only set the global setting once an IPIP pool has been created.  There is no reverse mechanism (i.e. the global setting is not disabled when all IPIP pools have been deleted ... but you can use the calicoctl config option to disable it if necessary).

I'm not 100% convinced we need a calicoctl change for this - the only one I can think of is to optionally install the module if you specify a different "--fix" flag on the check status command.

Any thoughts?

**Comment by spikecurtis** [comment]
I'm not sure what you're asking.  Is it "do we need to deal with the fact that the user may not have installed the `ipip` kernel mod when they add an IPIP pool?"  If so, then yes we do.

Or, are you asking "do we need to build the reverse mechanism so support is disabled automatically when the last IPIP pool is removed?"  For that one, I don't really think we do.

**Comment by robbrockbank** [comment]
@spikecurtis   yeah sorry it was two separate points that i didn't do a good job of separating.

On the "reverse mechanism" to remove the ipip module - I don't think we need that either.

On the other point, I was wondering what we should do about the "calicoctl check system --fix" command.  At the moment, this installs the ipip kernel module - but arguably we may want this particular one to be an optional install - e.g. by adding another flag to the command.  I'm inclined to leave as is - have the --fix option attempt to install everything that *might* be required.  If you want a less heavy handed approach, run without the "--fix" option and install the modules that you require.

Any thoughts?

**Comment by spikecurtis** [comment]
Yes, I'm inclined to leave the `check system --fix` command as is.

**Comment by robbrockbank** [comment]
Closing.

Fixed by #522 and change to libcalico to only set the global ipip flag when an IP pool is added that requires it.

**Comment by spikecurtis** [comment]
Do we check for the `ipip` module when the user adds a IP pool that requires it?
