### ISSUE TITLE
label names need encoding for compatability with felix

### ISSUE THREAD

**Issue by djosborne** [projectcalico/calico-docker#370]
>In Kubernetes, label names are passed to Felix which use them as rule-names (for human readability). However, Kubernetes accepts the / character, which Felix will error on. Therefore, we need to encode the / character.

#369 is a temporary fix to this issue, but we need a more reliable encoding scheme that won't have collisions.

**Comment by caseydavenport** [comment]
Issued moved to the Calico-Kubernetes repo here: https://github.com/projectcalico/calico-kubernetes/issues/8
