### ISSUE TITLE
calicoctl documentation

### ISSUE THREAD

**Issue by loshkovskyi** [projectcalico/calico-docker#382]
Hello,

In our project I would like to link to the `calicoctl` documentation but I'm not able to find one. Is it something that you'd want to add? It could go here, for example: https://github.com/Metaswitch/calico-docker/tree/master/docs
Right now, I am referring to `calicoctl help` for more details.

Thank you.

**Comment by tomdee** [comment]
Yes, it's something we'd love to add. It's on our plan, but not likely to happen this week. Pull requests are of course welcome! The location you mention is the right place for it.

**Comment by tomdee** [comment]
Current work in progress is in a PR - https://github.com/projectcalico/calico-docker/pull/438

Comments are welcome!

**Comment by TrimBiggs** [comment]
PR #532 Should cover this when it goes in.

**Comment by TrimBiggs** [comment]
Fixed by #532

**Comment by loshkovskyi** [comment]
Awesome, thank you!
