### ISSUE TITLE
`profile member add` equivalent

### ISSUE THREAD

**Issue by flipchart** [projectcalico/calico-docker#398]
Since version 0.4.7 `profile member add` has been replaced with `endpoint profile append`. However, `profile member add` allowed one to use the container name, while `endpoint profile append` requires the endpoint id, which requires a second command to retrieve, i.e. `./calicoctl endpoint $(./calicoctl container xxx endpoint-id show) profile append xxx`. This is a bit messy and it would be great if we could get back a command that uses the container name to add containers to a profile

**Comment by robbrockbank** [comment]
Hi @flipchat,

Yes this is something we are aware of - it's partly a result of us trying to make the Calico profile management commands more generally applicable than to Calico with Docker containers.  This is still a work in progress and so we may add more container-centric commands to simplify the endpoint and profile manipulation, but this is not something we have decided.  We'll keep you posted.

Rob

**Comment by tomdee** [comment]
This has been fixed by adding profile commands under `calicoctl container`

```
calicoctl container --help
Usage:
  calicoctl container <CONTAINER> ip (add|remove) <IP> [--interface=<INTERFACE>]
  calicoctl container <CONTAINER> endpoint show
  calicoctl container <CONTAINER> profile (append|remove|set) [<PROFILES>...]
  calicoctl container add <CONTAINER> <IP> [--interface=<INTERFACE>]
  calicoctl container remove <CONTAINER>

```
