### ISSUE TITLE
Working with containers that are killed

### ISSUE THREAD

**Issue by flipchart** [projectcalico/calico-docker#403]
When managing containers manually via `calicoctl container add <container> <ip>`, if the container is killed for whatever reason, I can't reconnect that container to the calico network again. Trying `calicoctl contain add` again gives me the message "< container> has already been configured with Calico Networking.". If I try to remove it via `calicoctl container remove <container>` I get the error message:

```
Cannot find device "cali7657ee4439a"
Unexpected error executing command.

Traceback (most recent call last):
  File "<string>", line 92, in <module>
  File "/code/build/calicoctl/out00-PYZ.pyz/calico_ctl.container", line 96, in container
  File "/code/build/calicoctl/out00-PYZ.pyz/calico_ctl.container", line 242, in container_remove
  File "/code/build/calicoctl/out00-PYZ.pyz/pycalico.netns", line 81, in remove_veth
  File "/code/build/calicoctl/out00-PYZ.pyz/subprocess32", line 599, in check_call
CalledProcessError: Command '['ip', 'link', 'del', u'cali7657ee4439a']' returned non-zero exit status 1
```

calico version 0.5.3

**Comment by Symmetric** [comment]
I've just hit this problem as well. FTR, here are the manual steps required to patch up the etcd repository to work around this problem:

```
# This command removes the etcd IP allocation, but not the endpoint.
calicoctl container remove <container>

# note the endpoint id for your container
calicoctl endpoint show --detailed

# Remove the stale endpoint
etcdctl rm /calico/v1/host/<node hostname/IP>/workload/docker/<docker id>/endpoint/<ep id>
```

Now the `calicoctl container add` command should work correctly.
