### ISSUE TITLE
function container_ip_add() takes exactly 3 arguments but 4 given

### ISSUE THREAD

**Issue by ninjadq** [projectcalico/calico-docker#420]
The definition of `container_ip_add()` [here](https://github.com/projectcalico/calico-docker/blob/master/calico_containers/calico_ctl/container.py#L252), only have three arguments
But when you calling it, you passed it 4 args, [here](https://github.com/projectcalico/calico-docker/blob/master/calico_containers/calico_ctl/container.py#L74)

**Comment by TrimBiggs** [comment]
Yup, good spot.  I've fixed this up in #421
