### ISSUE TITLE
Hard to find endpoint by IP address

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico-docker#436]
While debugging some scale runs, I was finding that I often had the IP address of the container in-hand but it was difficult to get from that to the information about the container from calicoctl.

The best way I've found so far is:

* use ip route to find out what host the IP is on
* ssh onto that host 
  * get the host's hostname
  * use ip route again to get the caliXXX interface name
  * use `calicoctl endpoint show --hostname=...` and grep for the XXX part of the interface.

**Comment by robbrockbank** [comment]
We're currently working on an updated IPAM module that should allow for this reverse mapping.  Watch this space :-)

**Comment by tomdee** [comment]
An easier way than your process above could be to run endpoint show and pass in the container ID. e.g.
```
$ dist/calicoctl endpoint show --workload=`docker inspect --format '{{ .ID }}' test2` --detailed
+------------+-----------------+------------------------------------------------------------------+----------------------------------+----------------+-------------------+----------+--------+
|  Hostname  | Orchestrator ID |                           Workload ID                            |           Endpoint ID            |   Addresses    |        MAC        | Profiles | State  |
+------------+-----------------+------------------------------------------------------------------+----------------------------------+----------------+-------------------+----------+--------+
| gulfstream |      docker     | 17d7bea9dfbfed241ff9f15b0801e57a6878080565f5c00b394628721117e714 | f25a32ca42aa11e58d6d080027bf35cd | 192.168.0.1/32 | 7e:9a:95:e8:cf:7b |          | active |
+------------+-----------------+------------------------------------------------------------------+----------------------------------+----------------+-------------------+----------+--------+
```

The endpoint show command can be run on any host (but will still be quicker if you pass in the --hostname option). If you use docker inspect like in the example above then that needs to talk to the right docker daemon - i.e. one that knows about the container.

**Comment by fasaxc** [comment]
I didn't know the ID or name of the container, only its IP in this case.  I was debugging issues like "ping failed to 192.168.23.123" and that meant I needed to figure out who 192.168.23.123 was.

**Comment by tomdee** [comment]
Ok, makes sense.

The new IPAM code (which is used everywhere as of the 0.7.0 release) allows additional attributes to be stored against the allocated IPs.

So, we could add a calicoctl command along the lines of `calicoctl ipam info <IP>` which shows the attributes stored for an IP.

This of course requires you to be using IPAM and to store the additional info you want (in your case the endpoint ID) when allocating the IP address.
