### ISSUE TITLE
BIRD using excessive CPU at scale

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/calico-docker#444]
As the number of routes goes up, BIRD spends more and more time polling the kernel routing table.  At 25000 routes, for example, it averages out to 30% of a core in my tests.

Experimentally, I reduced the poll rate to once every 20s.  That caused bird to burst to 20% CPU once every 20s, which seems more reasonable.  Of course, it will then take longer to spot deleted routes.

I'm worried that the excessive polling may cause knock-on issues as well.  I'm investigating whether it has an effect on propagation and stability.

**Comment by fasaxc** [comment]
Can confirm, the poll is an issue for propagation: https://github.com/projectcalico/calico-bird/issues/9

I'm still testing the stability impact.

**Comment by fasaxc** [comment]
BIRD seems to get blocked while it's polling.  Observed it failing to service incoming BGP connections if the poll interval is too short.

**Comment by tomdee** [comment]
See this for the upstream issue - https://github.com/projectcalico/calico-bird/issues/9

**Comment by tomdee** [comment]
Closing as this is an upstream issue and it's not clear that it's a problem at our target scale.
