### ISSUE TITLE
calicoctl node detects incorrect IP in CoreOS Vagrant with Docker (default networking) guide

### ISSUE THREAD

**Issue by johnmccabe** [projectcalico/calico-docker#460]
Following the steps outlined in - https://github.com/projectcalico/calico-docker/blob/master/docs/getting-started/default-networking/Demonstration.md, you are prompted to start calico on both nodes with:

    sudo calicotl node

This results in both nodes detecting the incorrect IP 10.1.42.1 on startup.

    core@calico-01 ~ $ sudo calicoctl node
    No IP provided. Using detected IP: 10.1.42.1
    Calico node is running with id: e57d311697f4907691a9bcdde376c51a2382694f4e7a0159224dd369246c02e5

    core@calico-02 ~ $ sudo calicoctl node
    No IP provided. Using detected IP: 10.1.42.1
    Calico node is running with id: d350ed747cf81cc9980dfa4f336745ac8eddb80ffb85e922de0a598aff4a5e85

    core@calico-01 /var/log/calico/bird $ etcdctl get /calico/bgp/v1/host/calico-01/ip_addr_v4
    10.1.42.1
    core@calico-01 /var/log/calico/bird $ etcdctl get /calico/bgp/v1/host/calico-02/ip_addr_v4
    10.1.42.1

Attempting to ping a container in the same profile but on a different node then fails.

As suggested in IRC, explicitly specifying the each nodes IP address when starting calico fixes the problem.

    core@calico-01 ~ $ sudo calicoctl node --ip=172.17.8.101
    Calico node is running with id: 8792472445ddc1734524a1922546af74d44a0e5b6f6f49c9fca607a9b275b394
    core@calico-02 ~ $ sudo calicoctl node --ip=172.17.8.102
    Calico node is running with id: 6cf07463e18187a399669429df7895da4482670717ae317e5e00648d1b64045f

    core@calico-01 ~ $ etcdctl get /calico/bgp/v1/host/calico-01/ip_addr_v4
    172.17.8.101
    core@calico-01 ~ $ etcdctl get /calico/bgp/v1/host/calico-02/ip_addr_v4
    172.17.8.102

(This is with Vagrant 5.0.0r101573 on a freshly installed OSX10.10.5 mbp)

**Comment by TrimBiggs** [comment]
Thanks for this @johnmccabe.  Can you paste in the output from running `ip -4 addr` on each of the vagrant machines?  We may have a fix for this already that will be in our next release.

**Comment by johnmccabe** [comment]
Yeah just noticed #343 

```core@calico-01 ~ $ ip -4 addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default 
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic eth0
       valid_lft 82404sec preferred_lft 82404sec
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    inet 172.17.8.101/24 brd 172.17.8.255 scope global eth1
       valid_lft forever preferred_lft forever
4: docker0@NONE: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default 
    inet 10.1.42.1/16 scope global docker0
       valid_lft forever preferred_lft forever```

```core@calico-02 ~ $ ip -4 addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default 
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic eth0
       valid_lft 82433sec preferred_lft 82433sec
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    inet 172.17.8.102/24 brd 172.17.8.255 scope global eth1
       valid_lft forever preferred_lft forever
4: docker0@NONE: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default 
    inet 10.1.42.1/16 scope global docker0
       valid_lft forever preferred_lft forever```

Cheers!

**Comment by TrimBiggs** [comment]
Cool, this is exactly what I thought.  We've made a bug fix that is in the latest release of our libcalico library [here](https://github.com/projectcalico/libcalico/releases/tag/v0.1.4).  This should be fixed and in a new `calicoctl` release today.

For now, you can work around this by passing the `--ip` argument in the `calicoctl node` command:
```
core@calico-01 ~ $ sudo calicoctl node --ip=172.17.8.101
core@calico-02 ~ $ sudo calicoctl node --ip=172.17.8.102
```

I'll post an update in here once the release is out!

**Comment by johnmccabe** [comment]
This works entirely as expected in the v0.6.0 release, thanks!

**Comment by TrimBiggs** [comment]
Awesome!  I'll close this issue then.
