### ISSUE TITLE
Steps appending profiles to containers do not work in v0.5.5 CoreOS Vagrant with Docker Default Networking guide

### ISSUE THREAD

**Issue by johnmccabe** [projectcalico/calico-docker#461]
The CoreOS with Docker Default Networking Vagrant setup (https://github.com/projectcalico/calico-docker/blob/master/docs/getting-started/default-networking/Demonstration.md) lists commands to append profiles to containers which do not work in v0.5.5.

For example:

    core@calico-01 ~ $ calicoctl container workload-A profile append PROF_A_C_E
    Usage:
      calicoctl container <CONTAINER> ip (add|remove) <IP> [--interface=<INTERFACE>]
      calicoctl container <CONTAINER> endpoint-id show
      calicoctl container add <CONTAINER> <IP> [--interface=<INTERFACE>]
      calicoctl container remove <CONTAINER>

Using the endpoint profile set command works as expected:

    core@calico-02 ~ $ calicoctl endpoint show --detailed | grep faadb45a480f11e591fa08002775ba7b
    | calico-01 |      docker     | 4f9954bb20e52e7e5e7953e52a1ad5a5353ba96efe813d1debd195c3cb69f47a | faadb45a480f11e591fa08002775ba7b | 192.168.0.1/32 | 72:ef:5a:87:35:bd |            | active |

    core@calico-02 ~ $ calicoctl endpoint faadb45a480f11e591fa08002775ba7b  profile set PROF_A_C_E
    Profiles PROF_A_C_E set for faadb45a480f11e591fa08002775ba7b.

    core@calico-02 ~ $ calicoctl endpoint show --detailed | grep faadb45a480f11e591fa08002775ba7b
    | calico-01 |      docker     | 4f9954bb20e52e7e5e7953e52a1ad5a5353ba96efe813d1debd195c3cb69f47a | faadb45a480f11e591fa08002775ba7b | 192.168.0.1/32 | 72:ef:5a:87:35:bd | PROF_A_C_E | active |

**Comment by johnmccabe** [comment]
Closing this as invalid - the v0.5.5 tag instructions are correct. I wasn't running off master.

**Comment by robbrockbank** [comment]
@johnmccabe 

Hi John,

Apologies for that.  The current docs are for our master code base which has recently had those commands added.  We are in the process of creating a new release of calicoctl that will have these changes in - hopefully releasing today.

If you are in hurry to use the new commands, you could build your own calicoctl image (see https://github.com/projectcalico/calico-docker/blob/master/docs/Building.md).

Rob

**Comment by robbrockbank** [comment]
Aha! looks like you responded while I was typing that up :-)

**Comment by johnmccabe** [comment]
Ninja level backtracking skills closing that ticket :)
