### ISSUE TITLE
Example container in the documentation fails to start. 

### ISSUE THREAD

**Issue by ajaybhatnagar** [projectcalico/calico-docker#471]
I suspect it is because netmask used is 32 instead of 22 for the actual vlan. No way to specify netmask when starting calicoctl .

Actual network on node: 
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 02:00:0a:ec:85:ab brd ff:ff:ff:ff:ff:ff
    inet 10.236.133.171/22 brd 10.236.135.255 scope global eth0

Container connection attempt:
interface "tmpf1b52bec6e0" routes to ["10.236.133.171/32"]: network is down

root@calico-01:~# docker run --publish-service srvA.net1.calico --name workload-A -tid busybox
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
cf2616975b4a: Pull complete
6ce2e90b0bc7: Pull complete
8c2e06607696: Pull complete
Digest: sha256:df9e13f36d2d5b30c16bfbf2a6110c45ebed0bfa1ea42d357651bc6c736d5322
Status: Downloaded newer image for busybox:latest
e9138b34c7b36746d36461071ffa1e6017dec7624ac37321e5483fad6f004c4e
Error response from daemon: Cannot start container e9138b34c7b36746d36461071ffa1e6017dec7624ac37321e5483fad6f004c4e: failed sandbox add: failed to add interface tmpf1b52bec6e0 to sandbox: error setting interface "tmpf1b52bec6e0" routes to ["10.236.133.171/32"]: network is down
root@calico-01:~# docker version
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   6f8c448
 Built:        Tue Aug 25 16:28:35 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   6f8c448
 Built:        Tue Aug 25 16:28:35 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

OS:
root@calico-01:~# uname -r
3.16.0-46-lowlatency

**Comment by TrimBiggs** [comment]
Hi @ajaybhatnagar,

I've just reproduced the issue locally with the latest experimental docker from today, but I do not see this when I use experimental docker from Aug 11.  I'll dig into this and try to figure out what has changed with Docker.

If you'd like to continue using Calico with libnetwork, you can use a `docker` image from one of our releases.  We copied a couple of known, working docker binaries to releases [0.5.3](https://github.com/projectcalico/calico-docker/releases/tag/v0.5.3) from July 21 and [0.5.4](https://github.com/projectcalico/calico-docker/releases/tag/v0.5.4) from Aug. 5th (optimized for 64-bit Ubuntu).  These aren't the latest versions of Docker, but either should work.

I'll update when I have more information.

**Comment by TrimBiggs** [comment]
After some further digging, it's not clear to me what the underlying problem is here.  Our libnetwork expert is out of the office at the moment, but he may have some insight into this issue when he returns.

Keep watching this space!

**Comment by ajaybhatnagar** [comment]
Thanks Tim.
Ajay

**Comment by tomdee** [comment]
I've raised this issue with libnetwork https://github.com/docker/libnetwork/issues/485

**Comment by ajaybhatnagar** [comment]
Thanks Tom.

**Comment by TrimBiggs** [comment]
Can this now be closed since docker/libnetwork#485 is closed?

**Comment by ajaybhatnagar** [comment]
I will give it a try next week and let you know.
Thanks
Ajay

**Comment by tomdee** [comment]
We've retested this and found it to work. @ajaybhatnagar please reopen the issue if you're still hitting problems.
