### ISSUE TITLE
calicoctl checksystem should examine etcd version and warn

### ISSUE THREAD

**Issue by spikecurtis** [projectcalico/calico-docker#479]
There are some versions of etcd that have known problems.  As part of check-system we should check the running version of etcd and drop a warning if it isn't the version we recommend.

This means we would need to introduce the concept of a recommended version, do our testing with it, and be proactive about testing the new versions.

**Comment by tomdee** [comment]
Who knows what the problems are? And what should the recommended version be?

We're not (yet) relying on new features so we just use 2.0.11 in the STs - can that be our minimum version https://github.com/coreos/etcd/releases/tag/v2.0.11

Do we need the concept of a minimum version (i.e. the oldest that will still work) and a recommended (the oldest that will perform well).

**Comment by spikecurtis** [comment]
The issue is overstated (sorry!); the only known problem is version 2.0.9, in which Compare-and-swap fails using `python-etcd`.

We could track minimum and recommended, but that increases our testing burden.  I'm not sure we'll get enough out of it to justify it.
