### ISSUE TITLE
Calico performance on the AWS public cloud

### ISSUE THREAD

**Issue by arjanschaaf** [projectcalico/calico-docker#481]
Hello,

I'm running some tests on a setup using Calico 0.6.0, CoreOS and Docker all hosted in a Amazon VPC environment. To get Calico working created the IP Pool like it was documented in the AWS guide:

```
calicoctl pool add 192.168.0.0/16 --ipip --nat-outgoing
```

I created an environment with 2 t2.micro VM's running in 1 EC2 availability zone. The containers can reach each other just fine over the calico network: great! The test I'm running is using **qperf**.

The first test I ran connected the containers using the host network by exposing the qperf server port on the first host with the following result:

```
tcp_bw:
    bw  =  127 MB/sec
tcp_lat:
    latency  =  210 us
```

Next was a run using the Calico network, instead of connecting to a port on the host, I connected the server and client containers on the 2 hosts using the IP addresses on the Calico network:

```
tcp_bw:
    bw  =  28.1 MB/sec
tcp_lat:
    latency  =  223 us
```

The latency is still great but the bandwidth took a heavy hit. I'm wondering: is this in line with performance results others have noticed? Or is this for a large part due to the **ipip** tunnel created to get Calico running on AWS?

**Comment by fasaxc** [comment]
The IPIP encapsulation does add a small overhead but we've not seen such a big drop in our testing (mainly on GCE with larger instances).  Do you see the same drop on a small or medium instance?  In my experience, the CPU throttling behaviour of micro instances makes their performance very erratic.  The small extra load may tip you over the threshold and result in throttling, for example.

**Comment by plwhite** [comment]
There are three possible limiting factors here on throughput

1. the cost of just having a veth and getting traffic out of it
2. the cost of IP in IP
3. the cost of getting traffic across the network.

Are you CPU limited (on either end) when you are running without 1 and 2 and getting 1Gb/s? You shouldn't be, but if you are then things could be problematic as you add the other factors in, especially with micro instances.

In our testing, we saw that cost of getting out of the veth is about a 50% increase in CPU (very roughly), and if you are struggling on CPU with the non-container test then I could just about believe a drop to 0.22Gb/s. A good deal worse than I would expect, but not utterly insane, especially if the micro instance gets throttled.

As Shaun says, it'd be very interesting to know whether going to more cores changes things radically or not.

**Comment by arjanschaaf** [comment]
So I re-ran the same test, but this time on a m4.xlarge instance: not throttling and a lot more power.
The qperf client is started with these params btw:

```
qperf <host-ip or calico-ip> -lp 4000 -ip 4001 tcp_bw tcp_lat
```

the results of 2 containers connected over the host interface without calico:

```
tcp_bw:
    bw  =  267 MB/sec
tcp_lat:
    latency  =  62 us
```

and again, but now using calico:

```
tcp_bw:
    bw  =  105 MB/sec
tcp_lat:
    latency  =  63.4 us
```

looking at the instance monitoring: CPU is very low during these tests.

**Comment by arjanschaaf** [comment]
@fasaxc @plwhite apparently it isn't what you are trying to measure, but is also how you measure it.
I switched from qperf to iperf3 (https://github.com/esnet/iperf) mainly because it allows you to better run your tests with multiple connections in parallel (128 is the maximum) and it is better equipped to run tests over a longer period. These are the first results on a m4.xlarge instance:

**2 containers on 2 different hosts connected over the host interface without Calico:**
```
iperf3 -c 10.150.16.17 -f g -t 600 -4 -P 128
[SUM]   0.00-600.00 sec  52.4 GBytes  0.75 Gbits/sec  1213279             sender
[SUM]   0.00-600.00 sec  52.3 GBytes  0.75 Gbits/sec                  receiver
```
with an average cpu load between 11 and 12 percent.

**2 containers on 2 different hosts connected using Calico:
```
iperf3 -c 192.168.0.1 -f g -t 600 -4 -P 128
[SUM]   0.00-600.00 sec  49.8 GBytes  0.71 Gbits/sec  11179679             sender
[SUM]   0.00-600.00 sec  49.5 GBytes  0.71 Gbits/sec                  receiver
```
with an average cpu load between 4 and 5 percent.

I consider this loss in bandwidth (-5%) very good and the increase in CPU load is OK too.

**Comment by plwhite** [comment]
Thanks for that - very interesting. We've used both qperf and iperf3 in the past, but settled on qperf because it is simpler and gives us good latency numbers. But we've not seen the two giving such different results before, something that I'll take a look into. My guess is that (as you say) it's related to multiple output streams, and the veth is getting blocked as the TCP buffers fill up. Why it would get blocked so much more than the case without IPIP I don't know given the latency numbers, but worth some more investigation here!
