### ISSUE TITLE
calicoctl doesn't provide a way to release old IPs

### ISSUE THREAD

**Issue by hectorj2f** [projectcalico/calico-docker#492]
Hello guys,

I am trying to reuse one IP from an old container but it seems that none of the existing commands is able to release this IP. I used `calicoctl remove container <CONTAINER_ID>` and `calicoctl container <CONTAINER_ID> ip remove <IP>` but I am still getting errors like the `IP has been already assigned`. I found a dirty workaround removing the assignment from etcd.

Is there a safer way to release that old IP ?

Thanks

**Comment by TrimBiggs** [comment]
Hi @hectorj2f,

Thanks for bringing this up.  When you say that the IP is from an old container, do you mean that the container has been removed from docker?  We currently do not have a command that frees the IP if the container no longer exists.

To free the IP, you can run the `calicoctl container remove <CONTAINER_ID>` command before deleting the container.  If you're seeing something different, please let us know.

It may be nice to add a command that frees old IPs that are no longer associated with containers.

**Comment by hectorj2f** [comment]
Hi @TrimBiggs. We use CoreOS, and we found some situations on which there are orphan IPs due to failures stopping/deleting systemd units. It could be really cool if you define a TTL for the IPs if there are not endpoints assigned to these orphan IPs. That could solve the problem.

**Comment by tomdee** [comment]
In general, `calicoctl remove container <CONTAINER_ID>` _should_ remove the IP assignments. If it's not, we should work out why.

**Comment by hectorj2f** [comment]
@tomdee It works we were killing the container before removing it from calico. 

However we faced a similar problem in a different scenario on which you have to reboot one machine (for whatever reason) and you want one container to get the same IP before rebooting. The container is gone but the IP is still assigned to calico based on etcd keys. In order to make this work, I have to explicitly remove that key prior the restart of such a systemd unit.

That's why I suggested to have a TTL or a healthcheck for the IPs to released those that are not used by any container in the network.

**Comment by tomdee** [comment]
I'm thinking that a `calicoctl ipam release <IP>` command would be generally useful here so I'll look at adding that for the next release. 

Are you aware of the libcalico library? It would provide a code interface rather than command line interface for doing things like releasing IPs. But am I right in thinking that much of the orchestration that you guys do is based around systemd, so offering you a python library might not be much help!

**Comment by tomdee** [comment]
I'm changing the title since I think we've established that `calicoctl remove container` does release the old IPs. You're looking for a way to clean up IP assignments, which might come in PR #510 or a way to remove stale endpoints (which will also release the IP) which could come in PR #507

**Comment by hectorj2f** [comment]
```
 But am I right in thinking that much of the orchestration that you guys do is based around systemd, so offering you a python library might not be much help!
```
Yes, you're right we use `systemd` for the orchestration.

``` You're looking for a way to clean up IP assignments, which might come in PR #510 or a way to remove stale endpoints (which will also release the IP) which could come in PR #507```

Thanks. I'll keep one eye on these PRs.
