### ISSUE TITLE
Unclear which calicoctl commands will work only on a container's host

### ISSUE THREAD

**Issue by djosborne** [projectcalico/calico-docker#499]
Its poorly documented which calicoctl commands will only work when run on the hosts that are running the targeted container. I believe its all the `calicoctl container` commands. But we only mention this restriction as a sidenote in one of the [Getting Started Guides](https://github.com/projectcalico/calico-docker/blob/master/docs/getting-started/default-networking/Demonstration.md)

>Note that whilst the calicoctl endpoint commands can be run on any Calico node, the calicoctl container commands will only work on the Calico node where the container is hosted.

This could arguably be placed in the `calicoctl container --help` message to improve clarity

**Comment by TrimBiggs** [comment]
PR #532 will cover which commands should be run on the host or any node.

**Comment by TrimBiggs** [comment]
Fixed by #532
