### ISSUE TITLE
Difficult to select version of Kubernetes plugin to use

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico-docker#513]
Currently, we can install our Kubernetes integration using the `--kubernetes` option on `calicoctl node`.

However, the calico-kubernetes plugin version is hard-coded in calicoctl with no way to configure it.  This is inflexible and leads to difficulty upgrading the plugin, which makes it hard to deploy bugfixes to users (a new release of calicoctl is required)

A few options here:
- `calicoctl node --kubernetes=version`
  - problem: docopt would require a value for `version`, so we couldn't set a default of `latest`.
- `calicoctl node --kubernetes --plugin-version=version` or something like that
- We could eliminate the `--kubernetes` flag altogether, use @Symmetric's work to containerize the kubernetes plugin and use DockerHub for distribution.
- ... ???

**Comment by robbrockbank** [comment]
For libnetwork we have a --libnetwork option to turn it on and --libnetwork-image=<image> to specify the image.  This seems preferable since in the normal use case you don't need to specify the image.

**Comment by caseydavenport** [comment]
@robbrockbank - yes, I'm leaning towards that option.

I'd propose:
```
calicoctl node --kubernetes --kube-plugin-version=<version>
```

The default for `--kube-plugin-version` would have to be hard-coded in `calicoctl` for now since there is no way to easily get the "latest" GitHub release (unlike for docker images).  If we containerize the plugin then we could change this behavior down the road.

I'm pretty keen to do this soon (and will do so myself if we agree on the syntax) - it slows us down significantly and makes it very difficult to release bugfixes. @Symmetric - thoughts?

**Comment by robbrockbank** [comment]
@caseydavenport This ties in with the proposal for streamlining the release process.  In that I suggested we implement a PHP script accessible on projectcalico.org that get return the latest build of the binaries scraped from the CircleCI artifacts.

On the master branch of calico-docker, we really would refer to the latest (bleeding edge) build of the plugins rather than referring to the latest release.

**Comment by jsfeutz** [comment]
Please also add option to pull the plugin from an internal repo for those of us behind corporate firewalls.
