### ISSUE TITLE
Deploy calico docker plugin as container?

### ISSUE THREAD

**Issue by pwFoo** [projectcalico/calico-docker#524]
Is there a calico docker image or a dockerfile to deploy the plugin inside a container with all dependencies like etcd?

**Comment by alexhersh** [comment]
Hey pwFoo, sorry for the delay in responding. Our docker images for `calico-node` do not include an etcd deployment. Our guides offer some recommendations for installing etcd on your own. 

If you would like to take a look at our docker images and dockerfiles, they are listed on the Calico DockerHub.

+ [Default Docker Image](https://hub.docker.com/r/calico/node/)
+ [Libnetwork Docker Image](https://hub.docker.com/r/calico/node-libnetwork/)

Does this answer your question?
