### ISSUE TITLE
`Calicoctl endpoint <ep_id> (append|set|remove) profile` contains undocumented parameters

### ISSUE THREAD

**Issue by TrimBiggs** [projectcalico/calico-docker#558]
This came up after raising issue #557 

I imagine this command used to be merged with the `endpoint <ENDPOINT_ID> profile show command`, which would explain this and why the `<PROFILES>` param is optional here.

Something like this:
```
calicoctl endpoint <ENDPOINT_ID> profile (append|remove|set|show) [--host=<HOSTNAME>] 
    [--orchestrator=<ORCHESTRATOR_ID>] [--workload=<WORKLOAD_ID>]  [<PROFILES>...]
```

but this command should look like this:
```
calicoctl endpoint <ENDPOINT_ID> profile (append|remove|set) <PROFILES>...
```

If the endpoint is required, we should not need any additional information about the hostname/orchestrator_id/workload_id to know which endpoint we are working with.

**Comment by robbrockbank** [comment]
It is correct that the endpoint ID is generally sufficient to identify an endpoint.  However, performing an endpoint lookup based purely on the endpoint ID requires a linear search through the etcd datastore to locate the endpoint.

Whilst this is OK for testing by hand, it does not make sense in a large deployment where there will be an orchestration layer.  In this case you can specify all of the IDs for faster lookup (no linear scan required).
