### ISSUE TITLE
It should be possible to set up a node without starting calico (felix/bird/confd)

### ISSUE THREAD

**Issue by tomdee** [projectcalico/calico-docker#564]
Operators may want to choose their own way of deploying the `calico-node` components i.e. felix, bird and confd. We currently only support using a docker container, but we do have native packages in our openstack repos. In addition to running the components natively, operators may want to use other container formats such as rkt.

The expected way that we'll support this is to add a new `calicoctl node --runtime=<RUNTIME>` command. It can take the following values
* docker - which is the current and default behaviour
* none - which doesn't run felix/bird/confd at all.

It future we may add other options.

**Comment by spikecurtis** [comment]
+1
