### ISSUE TITLE
Add help strings to the Makefile

### ISSUE THREAD

**Issue by alexwlchan** [projectcalico/calico-docker#576]
It would make it substantially easier to ramp-up on calico-docker development if there was a `help` target describing the different targets and options.

Here's an example of what I'm thinking of, from the docs Makefile in the main calico repo:

<pre><code><strong>(calico) metaswitch at hermione.linode.co.uk in ~/c/docs on git:master
$ make help</strong>
Please use `make &lt;target>' where &lt;target> is one of
  html       to make standalone HTML files
  dirhtml    to make HTML files named index.html in directories
  singlehtml to make a single large HTML file
  pickle     to make pickle files
  json       to make JSON files
  htmlhelp   to make HTML files and a HTML help project
  qthelp     to make HTML files and a qthelp project
  devhelp    to make HTML files and a Devhelp project
  epub       to make an epub
  latex      to make LaTeX files, you can set PAPER=a4 or PAPER=letter
  latexpdf   to make LaTeX files and run them through pdflatex
  latexpdfja to make LaTeX files and run them through platex/dvipdfmx
  text       to make text files
  man        to make manual pages
  texinfo    to make Texinfo files
  info       to make Texinfo files and run them through makeinfo
  gettext    to make PO message catalogs
  changes    to make an overview of all changed/added/deprecated items
  xml        to make Docutils-native XML files
  pseudoxml  to make pseudoxml-XML files for display purposes
  linkcheck  to check all external links for integrity
  doctest    to run all doctests embedded in the documentation (if enabled)</code></pre>

I'd try to do this myself, but I only know a handful of the commands so far, and I don't have time to work them all out right now.

**Comment by tomdee** [comment]
Fixed
