### ISSUE TITLE
Can Multitenant network created using calico

### ISSUE THREAD

**Issue by vijaykumar0690** [projectcalico/calico-docker#579]
Hi team,

Just want to know using calico multi tenant network can be created.
E.g. two users launching there cluster in mesos
Both using 172.16.0.1/16 segment and both cannot overlap and reach other .

It should be isolated.

Regards,
Vijay

**Comment by spikecurtis** [comment]
Hi Vijay,

What you're asking is definitely possible in principle with Calico's policy model, but the Mesos plug-in is not set up to work that way.  Right now, the isolation model for Mesos is to define "network groups" (see https://github.com/mesosphere/net-modules) that containers are placed in.  They can reach other members of groups they are in, but not workloads in groups they are not members of.

It sound like you're talking about launching two separate Mesos clusters, right?  This shouldn't be a problem for Calico, but if the you used the same network group name on both clusters, workloads in the group would be able to reach each other, even if they are in different clusters.

It might be possible to accommodate such a use case, but I would want to understand it better.  Feel free to reach out on IRC (#calico on freenode) or our public Slack at https://calicousers-slackin.herokuapp.com/ if you want to chat more.

Spike
