### ISSUE TITLE
Missing / Leftout docker.sh script in libnetwork cloud-config

### ISSUE THREAD

**Issue by crisidev** [projectcalico/calico-docker#581]
Hello,
libnetwork cloud config https://github.com/projectcalico/calico-docker/blob/master/docs/getting-started/libnetwork/cloud-config/user-data-others#L37 contains a missing / leftout script: docker.sh.

This causes coreos to fail provisioning of any node apart from the first.

**Comment by robbrockbank** [comment]
Fixed by #583

**Comment by robbrockbank** [comment]
@crisidev - thanks for the issue - this is now fixed.

**Comment by crisidev** [comment]
Thanks for the quick fix!
