### ISSUE TITLE
Calico-docker docs should point to calico-mesos docs

### ISSUE THREAD

**Issue by vijaykumar0690** [projectcalico/calico-docker#582]
Hi Team,

Can we have a document for calico with mesos integration.
On the future plans of having tenant wise seperation of overlapping ipv4s.
Wonderful design and thinking.When the future plan will be implemented in Calico.

If its implemented how we can have the tenant wise separation configured in mesos.

Regards,
Vijay

**Comment by djosborne** [comment]
Hi Vijay, we are working on documentation now, you can take a peak at our WIP over at [calico-docker PR#19](https://github.com/projectcalico/calico-mesos/pull/19)

**Comment by djosborne** [comment]
Closing, now that our [calico-mesos documentation](https://github.com/projectcalico/calico-docker/tree/master/docs/mesos) has been published
