### ISSUE TITLE
Typo in cloud-config file of CoreOS with libnetwork

### ISSUE THREAD

**Issue by smakam** [projectcalico/calico-docker#608]
Hi
I was trying out the example specified in:
https://github.com/projectcalico/calico-docker/blob/master/docs/getting-started/libnetwork/Demonstration.md

In this directory:
calico-docker/docs/getting-started/libnetwork/cloud-config
In user-data-first:
etcd2:
    advertise-client-urls: http://$private_ipv4:2379,http://$private_ipv4:2379
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:2379

This has to be changed to:
etcd2:
    advertise-client-urls: http://$private_ipv4:2379,http://$private_ipv4:4001
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001

With the default file, etcd2 did not start because port number 2379 is repeated twice.
After this change, everything else worked fine.

Thanks
Sreenivas

**Comment by robbrockbank** [comment]
Thanks @smakam -  just fixing this now.

We just retired the use of the 4001 port fopr etcd in our demos, so the correct fix is to just remove these duplicates.  The 4001 port should not be necessary.

**Comment by robbrockbank** [comment]
Fixed by #609
