### ISSUE TITLE
can not work on centos vms

### ISSUE THREAD

**Issue by AdoHe** [projectcalico/calico-docker#614]
I have two vms, both are Centos 7, and they are running on my laptop. For the first vm, the hostname is `calico-01`, the  second vm hostname is `calico-02`, ip address for each vm is: `calico-01: 192.168.113.128`, `calico-02:192.168.113.129`, they can `ping` each other. Then I installed `docker 1.6` on both vms, and also installed `calicoctl` on both vms. Also the `etcd` in running at `calico-01`. I tried to test `calico` with steps below:
### start calicoctl service on each vm
on `calico-01` vm:
```
[root@calico-01 tony]# calicoctl node
No IP provided. Using detected IP: 192.168.113.128
Calico node is running with id: f26471e12586db980939031998ddcc21739c6e1d4b11b49aa847670427b6236b
```
on `calico-02` vm:
```
[root@calico-02 ~]# calicoctl node
No IP provided. Using detected IP: 192.168.113.129
Calico node is running with id: 4999282bacdc7374638f65a11acefc7d3e2f99b92c161c8d2328fc6271f9199b
```

### start containers on each vm
on `calico-01` vm:
```
[root@calico-01 tony]# docker run --net=none --name workload-A -tid busybox
dec56c307ea971db79e92bdf5e02d5005cf73ed18668334455cd9eb6cac72f6c
[root@calico-01 tony]# docker run --net=none --name workload-B -tid busybox
1d13983093325e4b04991ec3f26b1f34dbe22f1f74fb1a3dfafbc57ac9d2efec
```
on `calico-02` vm:
```
[root@calico-02 ~]# docker run --net=none --name workload-C -tid busybox
e40afd75906c0b03c5161e2f0d456831835f9de9df7fe58ceb221b849717fa61
[root@calico-02 ~]# docker run --net=none --name workload-D -tid busybox
77c964a7ce392fad229c00571e31c33f040514caf54d3e168f477a12a0810136
```

### assign ip address to containers:
on `calico-01` vm:
```
[root@calico-01 tony]# calicoctl container add workload-A 192.168.0.1
IP 192.168.0.1 added to workload-A
[root@calico-01 tony]# calicoctl container add workload-B 192.168.0.2
IP 192.168.0.2 added to workload-B
```
on `calico-02` vm:
```
[root@calico-02 ~]# calicoctl container add workload-C 192.168.0.3
IP 192.168.0.3 added to workload-C
[root@calico-02 ~]# calicoctl container add workload-D 192.168.0.4
IP 192.168.0.4 added to workload-D
```
### create profiles on one vm
on `calico-01` vm:
```
[root@calico-01 tony]# calicoctl profile add A_C
Created profile A_C
[root@calico-01 tony]# calicoctl profile add B_D
Created profile B_D
```

### add profile to containers
on `calico-01` vm:
```
[root@calico-01 tony]# calicoctl container workload-A profile append A_C
Profile(s) A_C appended.

[root@calico-01 tony]# calicoctl container workload-B profile append B_D
Profile(s) B_D appended.
```

on `calico-02` vm:
```
[root@calico-02 ~]# calicoctl container workload-C profile append A_C
Profile(s) A_C appended.

[root@calico-02 ~]# calicoctl container workload-D profile append B_D
Profile(s) B_D appended.
```
Then I test the network on `calico-01` vm:
```
[root@calico-01 tony]# docker exec workload-A ping -c 4 192.168.0.3
PING 192.168.0.3 (192.168.0.3): 56 data bytes

--- 192.168.0.3 ping statistics ---
4 packets transmitted, 0 packets received, 100% packet loss
```
and the kernel IP route table on each vm is:
calico-01:
```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         192.168.113.2   0.0.0.0         UG    1024   0        0 eno16777736
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.0.1     0.0.0.0         255.255.255.255 UH    0      0        0 caliaa4e48ea892
192.168.0.2     0.0.0.0         255.255.255.255 UH    0      0        0 calibceb8594892
192.168.113.0   0.0.0.0         255.255.255.0   U     0      0        0 eno16777736
```
calico-02:
```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         192.168.113.2   0.0.0.0         UG    1024   0        0 eno16777736
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.0.3     0.0.0.0         255.255.255.255 UH    0      0        0 calic708228a892
192.168.0.4     0.0.0.0         255.255.255.255 UH    0      0        0 calice30d6c4892
192.168.113.0   0.0.0.0         255.255.255.0   U     0      0        0 eno16777736
```
I am wondering what's the problem? anyone knows?

**Comment by robbrockbank** [comment]
Hi @AdoHe,  As a first step, could you run `calicoctl status` on each node and paste in the output.

**Comment by AdoHe** [comment]
@robbrockbank I run `calicoctl status` after the `calicoctl node`, and on both vms, I got such result:
```
calico-node container is running. Status: Up About a minute
Running felix version 1.2.0

IPv4 BGP status
Unable to connect to server control socket (/etc/service/bird/bird.ctl): Connection refused


IPv6 BGP status
Unable to connect to server control socket (/etc/service/bird6/bird6.ctl): Connection refused
```
I think cause is clearly: there is no such socket file created on my vm. is this problem related with some kernel module missing? I did run `calicoctl checksystem` before I run other containers, but no mistakes return.

**Comment by tomdee** [comment]
So it looks like bird is failing to run. Can you run `calicoctl diags` and send us the result?

**Comment by robbrockbank** [comment]
Hi @AdoHe,

Did you manage to run the `calicoctl diags` comands on the hosts.  If you do manage to run this, you could upload the diags to transfer.sh or similar and post the link here, or let me know if you'd rather send in a PM.

If you don't manage to gather the diags, we'll try and repro in house as soon as we can.

Rob

**Comment by tomdee** [comment]
I just tried to repro this problem on centos 7 but didn't hit any issues.

```
[calico@localhost ~]$ ./calicoctl version
0.10.0-dev
[calico@localhost ~]$ ./calicoctl status
calico-node container is running. Status: Up About a minute
Running felix version 1.2.1

IPv4 BGP status
+--------------+-----------+-------+-------+------+
| Peer address | Peer type | State | Since | Info |
+--------------+-----------+-------+-------+------+
+--------------+-----------+-------+-------+------+

IPv6 BGP status
+--------------+-----------+-------+-------+------+
| Peer address | Peer type | State | Since | Info |
+--------------+-----------+-------+-------+------+
+--------------+-----------+-------+-------+------+
```

**Comment by AdoHe** [comment]
@tomdee @robbrockbank sorry about reply so late. I tried `calicoctl 0.4.9`, it is ok. Later I will try to reproduce this issue and provide more information.

**Comment by robbrockbank** [comment]
Hi @AdoHe,

Was 0.4.9 the first version that you found in which it started working?  Did you try all of the later versions?

I'm just wondering if it would be possible for you to find the most recent version that it works for CentOS so I can see what changed in the next release.

We also released a v0.12.0 today - perhaps that may resolve the issue.

Rob

**Comment by AdoHe** [comment]
@robbrockbank I will try later version as soon as I can. And I will give you more feedback.

**Comment by robbrockbank** [comment]
@AdoHe Hi - did you ever manage to see if this was working for you?

**Comment by AdoHe** [comment]
@robbrockbank I tried v0.12.0, it is ok. I think we can close this issue.
