### ISSUE TITLE
Documentation doesn't say that Docker needs to be started with --cluster-store for libnetwork to work

### ISSUE THREAD

**Issue by ajaybhatnagar** [projectcalico/calico-docker#627]
Trying to setup demo Calico with libnetwork  as per link below but getting error on getting pools config. Other setup of etcd, docker and pre-req have been completed. OS is Ubuntu3.16.0-52-lowlatency.

https://github.com/projectcalico/calico-docker/blob/master/docs/getting-started/libnetwork/Demonstration.md

```
root@calico-00:~# docker -v
Docker version 1.9.0, build 76d6bc9
root@calico-00:~# docker ps
CONTAINER ID        IMAGE                           COMMAND               CREATED             STATUS              PORTS               NAMES
c620cb9e5f04        calico/node-libnetwork:latest   "./start.sh"          5 minutes ago       Up 5 minutes                            calico-libnetwork
aab932f32e5a        calico/node:latest              "/sbin/start_runit"   5 minutes ago       Up 5 minutes                            calico-node
root@calico-00:~# docker network create --driver=calico --subnet=192.168.0.0/24 net1
Error response from daemon: error getting pools config from store during init: store for address space GlobalDefault not found
```

**Comment by tomdee** [comment]
This looks like a problem with how you've started docker. What options did you pass to the docker daemon when you started it?

**Comment by ajaybhatnagar** [comment]
Docker demon running with defaults only. Did not see any spl startup option in docs/blog.

Sent from my BlackBerry 10 smartphone on the Rogers network.
From: Tom Denham
Sent: Monday, November 16, 2015 17:21
To: projectcalico/calico-docker
Reply To: projectcalico/calico-docker
Cc: Ajay Bhatnagar
Subject: Re: [calico-docker] Demo startup with libnetwork fails. (#627)



This looks like a problem with how you've started docker. What options did you pass to the docker daemon when you started it?

**Comment by tomdee** [comment]
You're right - it should be documented on this page - https://github.com/projectcalico/calico-docker/blob/master/docs/getting-started/libnetwork/EnvironmentSetup.md

You can see how we configure Ubuntu using Vagrant here - https://github.com/projectcalico/calico-docker/blob/master/docs/getting-started/libnetwork/vagrant-ubuntu/Vagrantfile#L70

**Comment by ajaybhatnagar** [comment]
Thanks Tom for input. I was able to get it going.
