### ISSUE TITLE
After creating multihost calico demo docker containers they are unable to reach 

### ISSUE THREAD

**Issue by ajaybhatnagar** [projectcalico/calico-docker#633]
On node1
```
root@calico-01:/mnt# docker ps
CONTAINER ID        IMAGE                           COMMAND               CREATED             STATUS              PORTS               NAMES
3b60871450b2        busybox                         "sh"                  45 seconds ago      Up 44 seconds                           workload-A
63e5e4af97d0        calico/node-libnetwork:latest   "./start.sh"          29 minutes ago      Up 29 minutes                           calico-libnetwork
4167f753425f        calico/node:latest              "/sbin/start_runit"   29 minutes ago      Up 29 minutes                           calico-node
```

On node 2
```
root@calico-02:~# docker ps
CONTAINER ID        IMAGE                           COMMAND               CREATED              STATUS              PORTS               NAMES
a62aead1855d        busybox                         "sh"                  About a minute ago   Up About a minute                       workload-Z
c0cc8ca65442        calico/node-libnetwork:latest   "./start.sh"          7 minutes ago        Up 7 minutes                            calico-libnetwork
ae8f3c0faad7        calico/node:latest              "/sbin/start_runit"   7 minutes ago        Up 7 minutes                            calico-node
```
Ping test fails:
```
root@calico-01:/mnt# docker exec workload-A ping -c 4 workload-Z.net1
PING workload-Z.net1 (192.168.0.5): 56 data bytes

ETCD setup is fine and reachable from the nodes:
root@calico-01:/mnt# telnet 10.236.133.87 2379
Trying 10.236.133.87...
Connected to 10.236.133.87.
Escape character is '^]'.

ETCD_AUTHORITY=10.236.133.87:2379
etcd logs:
2015-11-17 20:40:48.608777 I | etcdserver: setting up the initial cluster version to 2.2
2015-11-17 20:40:48.624911 N | etcdserver: set the initial cluster version to 2.2
2015-11-17 20:40:48.625022 I | etcdserver: published {Name:default ClientURLs:[http://10.236.133.87:2379]} to cluster 7e27652122e8b2ae
```

Where to find debug logs ? There is no firewall between nodes.

**Comment by robbrockbank** [comment]
Hi @ajaybhatnagar,

Could you run `calicoctl status` and share the output here.  Also, could you perhaps run `calicoctl diags` on both hosts and send us the output?

Most of the logs of interest are in the calico-node container - however, we volumne mount the log directory, so you simply look at the logs on your host in /var/log/calico.

**Comment by ajaybhatnagar** [comment]
Here is the status. Have the diag files also ceated. Let me know where should I put them .
On first node creating the docker container fails though docker ps command does not list any. Remove the container and rerun the same command , it fails again.

Thanks
Ajay

root@calico-00:~# calicoctl status
calico-node container is running. Status: Up 2 hours
Running felix version 1.2.0

IPv4 BGP status
+---------------+-------------------+-------+----------+-------------+
|  Peer address |     Peer type     | State |  Since   |     Info    |
+---------------+-------------------+-------+----------+-------------+
| 10.236.133.88 | node-to-node mesh |   up  | 22:57:16 | Established |
| 10.236.133.89 | node-to-node mesh |   up  | 21:40:27 | Established |
| 10.236.133.90 | node-to-node mesh |   up  | 21:39:56 | Established |
+---------------+-------------------+-------+----------+-------------+

IPv6 BGP status
+--------------+-----------+-------+-------+------+
| Peer address | Peer type | State | Since | Info |
+--------------+-----------+-------+-------+------+
+--------------+-----------+-------+-------+------+

On node 1 root@calico-01:~# docker run --net net1 --name workload-A -tid busybox
ff4ca742b0f5c64280985843c9748211b12a42b8ed15011073c76bc8f9c3b30c
Error response from daemon: Cannot start container ff4ca742b0f5c64280985843c9748211b12a42b8ed15011073c76bc8f9c3b30c: container already connected to network net1
root@calico-01:~# docker ps
CONTAINER ID        IMAGE                           COMMAND               CREATED             STATUS              PORTS               NAMES
d5454fe32554        calico/node-libnetwork:latest   "./start.sh"          4 minutes ago       Up 4 minutes                            calico-libnetwork
c3c1bb4824db        calico/node:latest              "/sbin/start_runit"   4 minutes ago       Up 4 minutes                            calico-node

On Node 2 root@calico-02:~# docker ps
CONTAINER ID        IMAGE                           COMMAND               CREATED             STATUS              PORTS               NAMES
3c5be9c1b25f        busybox                         "sh"                  2 minutes ago       Up About a minute                       workload-B
c0cc8ca65442        calico/node-libnetwork:latest   "./start.sh"          About an hour ago   Up About an hour                        calico-libnetwork
ae8f3c0faad7        calico/node:latest              "/sbin/start_runit"   About an hour ago   Up About an hour                        calico-node

On Node 3:

root@calico-03:~# docker exec workload-C ping -c 4 workload-B.net1
PING workload-B.net1 (192.168.0.5): 56 data bytes

--- workload-B.net1 ping statistics ---
4 packets transmitted, 0 packets received, 100% packet loss
root@calico-03:~# docker ps
CONTAINER ID        IMAGE                           COMMAND               CREATED              STATUS              PORTS               NAMES
757ee78f0e0c        busybox                         "sh"                  About a minute ago   Up About a minute                       workload-C
4e11553f33c3        calico/node-libnetwork:latest   "./start.sh"          About an hour ago    Up About an hour                        calico-libnetwork
84d79b9827c4        calico/node:latest              "/sbin/start_runit"   About an hour ago    Up About an hour                        calico-node

**Comment by robbrockbank** [comment]
Hi @ajaybhatnagar,

I haven't had a chance to look at the diags just at the moment, but I have just hit an issue myself with the latest images - in particular images that are using the latest release of calico.  I've raise an issue with the core calico folk about that.

From your output, it looks as though you are using the latest images from the HEAD of master.  Until that is resolved, you might want to use the latest actual release of calicoctl - see release v0.11.0 here: https://github.com/projectcalico/calico-docker/releases/tag/v0.11.0

**Comment by ajaybhatnagar** [comment]
Problem is in release v0.11.0, able to connect with release v.0.10.0
Thanks
Ajay

**Comment by robbrockbank** [comment]
Hi @ajaybhatnagar,

Thank you for the update.  I've just noticed that the documentation links for v0.11.0 were not updated correctly, so it is quite possible that the binaries you were using were actually from the master branch which was not working (although it should be working now).

I'll get the docs fixed up for v0.11.0 - hopefully this will resolve the problem, but it's good to know that you can use v0.10.0 for now.

Rob

**Comment by ajaybhatnagar** [comment]
I specifically tried with v0.11‎.0 links provided first then downgraded to v0.10
Thanks
Ajay

Sent from my BlackBerry 10 smartphone on the Rogers network.
From: robbrockbank
Sent: Wednesday, November 18, 2015 18:40
To: projectcalico/calico-docker
Reply To: projectcalico/calico-docker
Cc: Ajay Bhatnagar
Subject: Re: [calico-docker] After creating multihost calico demo docker containers they are unable to reach (#633)

‎

Hi @ajaybhatnagar<https://github.com/ajaybhatnagar>,

Thank you for the update. I've just noticed that the documentation links for v0.11.0 were not updated correctly, so it is quite possible that the binaries you were using were actually from the master branch which was not working (although it should be working now).

I'll get the docs fixed up for v0.11.0 - hopefully this will resolve the problem, but it's good to know that you can use v0.10.0 for now.

Rob

**Comment by ajaybhatnagar** [comment]
Is it possible to use Zookeeper in place of ETCD , if yes, what changes may be needed?
Thanks
Ajay

**Comment by robbrockbank** [comment]
@ajaybhatnagar 

We currently only support etcd.

**Comment by robbrockbank** [comment]
@ajaybhatnagar 

We've just released v0.12.0 which I believe will address the problem you were having with master and with v0.11.0.

I'll close the issue, but if you are still having problem please reopen and update.

Rob

**Comment by ajaybhatnagar** [comment]
Thanks  Rob.
I will verify it and update if necessary.
Ajay

**Comment by ajaybhatnagar** [comment]
It worked on v0.12.0 however when all nodes were running v0.12.0 not in mixed mode with some nodes on  v.010.0 and some on v0.12.0. Probably some incompatibility between versions.
Thanks
