### ISSUE TITLE
Host cannot ping to container

### ISSUE THREAD

**Issue by frostynova** [projectcalico/calico-docker#636]
Calico 0.10 + libnetwork + Docker 1.9

On the host can not ping the container. But tcpdump show the container has received the arp packet.

With some testing, i found more than one network interfaces in the container:

```
[root@baa4a1620218 /]# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: tunl0: <NOARP> mtu 0 qdisc noop state DOWN
    link/ipip 0.0.0.0 brd 0.0.0.0
10: cali0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff
    inet 172.20.0.2/16 scope global cali0
       valid_lft forever preferred_lft forever
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link
       valid_lft forever preferred_lft forever
13: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
    link/ether 02:42:ac:12:00:02 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.2/16 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe12:2/64 scope link
       valid_lft forever preferred_lft forever

[root@baa4a1620218 /]# ip route
default via 172.18.0.1 dev eth1
172.18.0.0/16 dev eth1  proto kernel  scope link  src 172.18.0.2
172.20.0.0/16 dev cali0  proto kernel  scope link  src 172.20.0.2
```

**eth1** seems to be the docker bridge, and the default route point to it. I guess it is why the ping failed

In this issue https://github.com/docker/libnetwork/issues/666 , it said 

> if the network plugin doesn’t handle the default gateway for the container, libnetwork will provide that as a service to the container so that it gets external connectivity

**Comment by robbrockbank** [comment]
Hi @frostynova - could you let me know what steps you took to create the container etc?  I'm surprised that there are two interfaces if you are using libnetwork.

**Comment by robbrockbank** [comment]
Hi @frostynova,

Actually this is similar to a discussion on the libnetwork-plugin repo (https://github.com/projectcalico/libnetwork-plugin/issues/21).  We are currently working on an IPAM driver for libnetwork, using this driver will default to the previous behavior of a single cali interface.

**Comment by robbrockbank** [comment]
Hi @frostynova,

If you now use the Calico IPAM driver (release in v0.12.0) we always route via the host vRouter rather than the Docker gateway bridge.

I believe this should resolve your issue.  I'll close the issue, but please re-open and update if that is not the case.
