### ISSUE TITLE
Documentation not updated correctly for v0.11.0

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/calico-docker#639]
For example:

Links to calicoctl binary are still referencing the latest build from master
Page header still says the docs are for master.

There may be other issues.

**Comment by caseydavenport** [comment]
Version still reports v0.10.0-dev

**Comment by robbrockbank** [comment]
Not fixed in v0.11.0 - but v0.12.0 is now released, and version string updates seem to have been resolved.
