### ISSUE TITLE
restart a container,how to acquire old  ipaddress automatically

### ISSUE THREAD

**Issue by jaywayjayway** [projectcalico/calico-docker#655]
restart a container,how to acquire old  ipaddress automatically

**Comment by robbrockbank** [comment]
@jaywayjayway 

Hi,  just to clarify, are you using the "libnetwork", or "default docker networking" approach to add you containers into Calico.

I assume you are using the "default docker networking" approach.  In this case you'll need to remove your container from Calico using the ```calicoctl container remove``` command, and then re-add it back into the Calico network using the ```calicoctl container add``` command.

**Comment by robbrockbank** [comment]
@jaywayjayway 

Hi, Just following up with your issue.  Did my previous comment make sense?  Just want to make sure you aren't blocked on anything.

Rob

**Comment by robbrockbank** [comment]
Hi @jaywayjayway - I'm closing this issue as I hope I addressed your question above.  However, if it didn't make sense, or you need more information - please feel free to re-open and update the issue.
