### ISSUE TITLE
no need to use export DOCKER_HOST=localhost:2377 ?

### ISSUE THREAD

**Issue by AdoHe** [projectcalico/calico-docker#659]
FYI. is there any need to use `export DOCKER_HOST=localhost:2377` command after we call `sudo calicoctl node` command? If no need, how `calico` can intercept the docker api?

**Comment by robbrockbank** [comment]
@AdoHe 

Not any more.

From version 1.9, Docker has a native networking framework (based on libnetwork) that allows you to write networking and IPAM drivers for Docker containers.  If you are using Calico with libnetwork (e.g. by running ```calicoctl node --libnetwork```) we spin up a container (calico-libnetwork) that contains a network driver that hooks directly into Dockers native networking framework.  Have a look at the libnetwork demonstration in this repo.

Prior to Docker 1.9 release we had a release of calico-docker that allowed you to use Powerstrip to intercept the Docker requests.  In that case you would need to export the DOCKER_HOST as you mention - but we have retired that approach for calico-docker.

Our "default Docker Networking" demonstration (which is badly named - it's really Docker with no networking) has an alternative approach for networking containers with Calico.  In this case Docker performs no networking, and you use calicoctl to explicitly add the container to the Calico network.  No Docker requests are intercepted in this case.

**Comment by AdoHe** [comment]
@robbrockbank Get it! Thanks very much.
