### ISSUE TITLE
etcdStructure.md is out of date

### ISSUE THREAD

**Issue by TrimBiggs** [projectcalico/calico-docker#671]
The structure of etcd has changed since this doc was written.  The ipam paths are significantly different with the introduction of ipam blocks, and some naming has also changed, such as changing `/calico/v1/host/<host>/bird_ip` to `/calico/v1/host/<host>/bird_ip`

**Comment by robbrockbank** [comment]
Not sure what you mean about the bird_ip naming.

**Comment by TrimBiggs** [comment]
Whoops, I meant `/calico/v1/host/<host>/ipv4_addr` to `/calico/v1/host/<host>/bird_ip`.  I made a comment about it in the PR.
