### ISSUE TITLE
symbol lookup error

### ISSUE THREAD

**Issue by euprogramador** [projectcalico/calico-docker#679]
I downloaded the calicoctl and run'm getting this:

\#./calicoctl 
*sh: symbol lookup error: /lib/x86_64-linux-gnu/libncurses.so.5: undefined symbol: _nc_putchar
sh: symbol lookup error: /lib/x86_64-linux-gnu/libncurses.so.5: undefined symbol: _nc_putchar
sh: symbol lookup error: /lib/x86_64-linux-gnu/libncurses.so.5: undefined symbol: _nc_putchar
sh: symbol lookup error: /lib/x86_64-linux-gnu/libncurses.so.5: undefined symbol: _nc_putchar
sh: symbol lookup error: /lib/x86_64-linux-gnu/libncurses.so.5: undefined symbol: _nc_putchar
calicoctl*

Override the host:port of the ETCD server by setting the environment variable
ETCD_AUTHORITY [default: 127.0.0.1:2379]

Usage: calicoctl <command> [<args>...]

    status            Print current status information
    node              Configure the main calico/node container and establish Calico networking
    container         Configure containers and their addresses
    profile           Configure endpoint profiles
    endpoint          Configure the endpoints assigned to existing containers
    pool              Configure ip-pools
    bgp               Configure global bgp
    ipam              Configure IP address management
    checksystem       Check for incompatibilities on the host system
    diags             Save diagnostic information
    version           Display the version of calicoctl
    config            Configure low-level component configuration

See 'calicoctl <command> --help' to read about a specific subcommand.

what sh: symbol lookup error: /lib/x86_64-linux-gnu/libncurses.so.5: undefined symbol: _nc_putchar?

**Comment by robbrockbank** [comment]
Hi @euprogramador 

I've not seen that before.  Sounds like an incompatibility between the host OS and the calicoctl binary.

Could you let me know a little more about your OD/Kernel, and include the output from `uname -a`

**Comment by euprogramador** [comment]
i am using debian jessie, Interestingly, I reinstalled the system in debian 7 and upgraded to the debian 8 and work in any required form .
