### ISSUE TITLE
Kubernetes-plugin: allow multiple etcd-peers [HA]

### ISSUE THREAD

**Issue by maklemenz** [projectcalico/calico-docker#688]
The [plugin documentation](https://github.com/projectcalico/calico-docker/blob/master/docs/kubernetes/PluginConfiguration.md) says it is not possible to define multiple etcd-endpoints. This is a problem to me since this particular node could be down.

This could possibly be done without breaking anything by accepting comma separated values in ETCD_AUTHORITY.

Adding a haproxy doesn't seem to be the right thing to do, since every etcd-client-api implementation I know allows to set multiple peers and handles them somewhat correctly.

**Comment by caseydavenport** [comment]
Hi @maklemenz - At the moment, neither the kubernetes plugin nor the `calico/node` container support a list of `etcd` endpoints.  We recommend using an `etcd` proxy for connecting to multiple `etcd` endpoints.

I believe this is also the way CoreOS recommends connecting to a clustered `etcd`.

https://github.com/coreos/etcd/blob/master/Documentation/proxy.md

**Comment by maklemenz** [comment]
Hi @caseydavenport, thank you for that information. I'll look into the configuration of etcd-instances as proxies.

**Comment by pnegahdar** [comment]
Any updates to this?

**Comment by caseydavenport** [comment]
@pnegahdar this is now supported by all Calico components.  See the documentation for details: http://docs.projectcalico.org/v2.0/reference/node/configuration

> ETCD_ENDPOINTS: A comma separated list of etcd endpoints (optional, defaults to http://127.0.0.1:2379)

**Comment by pnegahdar** [comment]
We recently had a network plane outage after a single etcd (in the comma separated list) failed The cluster itself was healthy. I plan on taking a look at how the endpoints are used by calico, if you're already familiar any advice would  be great.

**Comment by caseydavenport** [comment]
@pnegahdar interesting, I would not expect a single node failure in a clustered etcd to cause Calico to stop working.

Any idea which component stopped working properly?  What were your symptoms?
